import type { Company } from "@shared/schema";

export const mockCompanies: Company[] = [
  {
    id: "1",
    name: "Luminance AI",
    domain: "luminance.com",
    description: "AI-powered legal technology platform automating contract review, negotiation, and analysis for law firms and in-house legal teams worldwide.",
    industry: "Legal Tech",
    stage: "Series C",
    foundedYear: 2015,
    employeeCount: "201-500",
    location: "London, UK",
    fundingTotal: "$120M",
    lastFundingDate: "2024-09-15",
    tags: ["AI/ML", "Legal", "Enterprise", "NLP"],
    signals: [
      { id: "s1", type: "funding", title: "Raised $40M Series C", description: "Led by Forestay Capital with participation from existing investors.", date: "2024-09-15", source: "TechCrunch" },
      { id: "s2", type: "hiring", title: "Engineering team expansion", description: "15 new engineering roles posted across ML and backend.", date: "2024-11-01" },
      { id: "s3", type: "product", title: "Launched Auto-Negotiate feature", description: "New AI-powered contract negotiation tool for enterprise clients.", date: "2024-10-20" },
      { id: "s4", type: "partnership", title: "Partnership with Baker McKenzie", description: "Strategic partnership with top global law firm.", date: "2024-08-10" },
    ],
  },
  {
    id: "2",
    name: "Vercel",
    domain: "vercel.com",
    description: "Frontend cloud platform enabling developers to build and deploy web applications with serverless functions, edge computing, and seamless Git integration.",
    industry: "Developer Tools",
    stage: "Series D",
    foundedYear: 2015,
    employeeCount: "501-1000",
    location: "San Francisco, CA",
    fundingTotal: "$563M",
    lastFundingDate: "2024-05-16",
    tags: ["DevTools", "Cloud", "Serverless", "Frontend"],
    signals: [
      { id: "s5", type: "funding", title: "Raised $250M Series D", description: "Valuation reached $3.25B. Led by GV with participation from Greenoaks.", date: "2024-05-16", source: "Bloomberg" },
      { id: "s6", type: "product", title: "v0 AI code generation launch", description: "Released AI-powered UI generation tool.", date: "2024-03-01" },
      { id: "s7", type: "growth", title: "10M+ developers on platform", description: "Crossed 10 million developer accounts milestone.", date: "2024-07-15" },
    ],
  },
  {
    id: "3",
    name: "Mistral AI",
    domain: "mistral.ai",
    description: "European AI lab building open and commercial large language models, focused on efficiency and multilingual capabilities for enterprise deployment.",
    industry: "Artificial Intelligence",
    stage: "Series B",
    foundedYear: 2023,
    employeeCount: "51-200",
    location: "Paris, France",
    fundingTotal: "$528M",
    lastFundingDate: "2024-06-11",
    tags: ["AI/ML", "LLM", "Open Source", "Enterprise"],
    signals: [
      { id: "s8", type: "funding", title: "Raised $468M Series B", description: "Valuation reached $5.8B. Led by General Catalyst and Lightspeed.", date: "2024-06-11", source: "Reuters" },
      { id: "s9", type: "product", title: "Released Mixtral 8x22B", description: "New mixture-of-experts model with state-of-art performance.", date: "2024-04-17" },
      { id: "s10", type: "partnership", title: "Microsoft Azure partnership", description: "Models available on Azure AI services.", date: "2024-02-26" },
      { id: "s11", type: "hiring", title: "Research team growing", description: "20+ research scientist roles open across NLP and systems.", date: "2024-08-05" },
    ],
  },
  {
    id: "4",
    name: "Wiz",
    domain: "wiz.io",
    description: "Cloud security platform providing agentless visibility, risk assessment, and threat detection across multi-cloud environments for enterprise organizations.",
    industry: "Cybersecurity",
    stage: "Series D",
    foundedYear: 2020,
    employeeCount: "1001-5000",
    location: "New York, NY",
    fundingTotal: "$900M",
    lastFundingDate: "2024-05-02",
    tags: ["Security", "Cloud", "Enterprise", "SaaS"],
    signals: [
      { id: "s12", type: "funding", title: "Raised $300M at $12B valuation", description: "Largest cybersecurity startup round in 2024.", date: "2024-05-02", source: "WSJ" },
      { id: "s13", type: "growth", title: "ARR surpassed $500M", description: "Revenue growth of 100% year-over-year.", date: "2024-06-01" },
      { id: "s14", type: "press", title: "Google acquisition talks", description: "Reported $23B acquisition offer from Alphabet.", date: "2024-07-14", source: "WSJ" },
    ],
  },
  {
    id: "5",
    name: "Anthropic",
    domain: "anthropic.com",
    description: "AI safety company building reliable and interpretable AI systems, known for the Claude family of large language models and constitutional AI approach.",
    industry: "Artificial Intelligence",
    stage: "Series D",
    foundedYear: 2021,
    employeeCount: "501-1000",
    location: "San Francisco, CA",
    fundingTotal: "$7.6B",
    lastFundingDate: "2024-03-25",
    tags: ["AI/ML", "AI Safety", "LLM", "Enterprise"],
    signals: [
      { id: "s15", type: "funding", title: "Raised $2.75B Series D", description: "Amazon invested additional $2.75B, total Amazon investment $4B.", date: "2024-03-25", source: "CNBC" },
      { id: "s16", type: "product", title: "Claude 3 Opus released", description: "Most capable model with near-human performance on benchmarks.", date: "2024-03-04" },
      { id: "s17", type: "hiring", title: "Massive hiring push", description: "100+ open roles across research, engineering, and policy.", date: "2024-09-01" },
    ],
  },
  {
    id: "6",
    name: "Figma",
    domain: "figma.com",
    description: "Collaborative design platform for teams to create, prototype, and handoff UI designs in real-time with powerful multiplayer editing capabilities.",
    industry: "Design Tools",
    stage: "Late Stage",
    foundedYear: 2012,
    employeeCount: "1001-5000",
    location: "San Francisco, CA",
    fundingTotal: "$332M",
    lastFundingDate: "2021-06-24",
    tags: ["Design", "Collaboration", "SaaS", "Product"],
    signals: [
      { id: "s18", type: "product", title: "Figma AI features announced", description: "AI-powered design generation and auto-layout suggestions.", date: "2024-06-26" },
      { id: "s19", type: "growth", title: "4M+ paying users", description: "Continued growth after Adobe deal collapse.", date: "2024-04-01" },
      { id: "s20", type: "product", title: "Dev Mode enhancements", description: "New developer handoff features and code generation.", date: "2024-02-15" },
    ],
  },
  {
    id: "7",
    name: "Stripe",
    domain: "stripe.com",
    description: "Financial infrastructure platform providing payment processing, billing, and financial tools for internet businesses of all sizes globally.",
    industry: "FinTech",
    stage: "Late Stage",
    foundedYear: 2010,
    employeeCount: "5001-10000",
    location: "San Francisco, CA",
    fundingTotal: "$2.3B",
    lastFundingDate: "2023-03-15",
    tags: ["Payments", "FinTech", "API", "Enterprise"],
    signals: [
      { id: "s21", type: "growth", title: "Processed $1T+ in 2023", description: "Total payment volume exceeded $1 trillion for the first time.", date: "2024-01-15", source: "Forbes" },
      { id: "s22", type: "product", title: "Stripe Billing v2 launch", description: "Revamped subscription billing with usage-based pricing support.", date: "2024-04-24" },
      { id: "s23", type: "press", title: "IPO timeline discussions", description: "CEO hints at potential public offering in 2025.", date: "2024-10-03", source: "Bloomberg" },
    ],
  },
  {
    id: "8",
    name: "Notion",
    domain: "notion.so",
    description: "All-in-one workspace combining notes, docs, wikis, and project management with AI-powered writing assistance and team collaboration features.",
    industry: "Productivity",
    stage: "Series C",
    foundedYear: 2013,
    employeeCount: "501-1000",
    location: "San Francisco, CA",
    fundingTotal: "$343M",
    lastFundingDate: "2021-10-08",
    tags: ["Productivity", "Collaboration", "SaaS", "AI"],
    signals: [
      { id: "s24", type: "product", title: "Notion AI GA release", description: "AI writing assistant fully integrated across all workspaces.", date: "2024-02-01" },
      { id: "s25", type: "growth", title: "100M+ users milestone", description: "Reached 100 million users globally.", date: "2024-05-15" },
      { id: "s26", type: "product", title: "Notion Calendar launch", description: "Standalone calendar app integrating with Notion workspace.", date: "2024-01-18" },
    ],
  },
  {
    id: "9",
    name: "Databricks",
    domain: "databricks.com",
    description: "Unified data analytics platform combining data engineering, data science, and machine learning on a lakehouse architecture for enterprise scale.",
    industry: "Data & Analytics",
    stage: "Series I",
    foundedYear: 2013,
    employeeCount: "5001-10000",
    location: "San Francisco, CA",
    fundingTotal: "$4.1B",
    lastFundingDate: "2023-09-14",
    tags: ["Data", "Analytics", "AI/ML", "Enterprise"],
    signals: [
      { id: "s27", type: "growth", title: "ARR exceeded $1.6B", description: "50% year-over-year revenue growth driven by AI workloads.", date: "2024-03-01", source: "TechCrunch" },
      { id: "s28", type: "product", title: "DBRX open model released", description: "Open-source LLM competitive with GPT-3.5 performance.", date: "2024-03-27" },
      { id: "s29", type: "hiring", title: "AI division expansion", description: "Building dedicated generative AI product team.", date: "2024-07-01" },
    ],
  },
  {
    id: "10",
    name: "Linear",
    domain: "linear.app",
    description: "Modern project management and issue tracking tool built for high-performance software teams with keyboard-first design and real-time sync.",
    industry: "Developer Tools",
    stage: "Series B",
    foundedYear: 2019,
    employeeCount: "51-200",
    location: "San Francisco, CA",
    fundingTotal: "$52M",
    lastFundingDate: "2022-03-22",
    tags: ["DevTools", "Project Management", "SaaS", "Product"],
    signals: [
      { id: "s30", type: "product", title: "Linear Asks feature", description: "New triage system for managing incoming requests.", date: "2024-08-14" },
      { id: "s31", type: "growth", title: "Rapid enterprise adoption", description: "50% of Fortune 500 tech companies now using Linear.", date: "2024-06-01" },
      { id: "s32", type: "product", title: "AI-powered project insights", description: "Automated project status summaries and risk detection.", date: "2024-09-20" },
    ],
  },
  {
    id: "11",
    name: "Runway",
    domain: "runwayml.com",
    description: "Applied AI research company building generative AI tools for video creation, editing, and visual storytelling for creative professionals.",
    industry: "Creative AI",
    stage: "Series D",
    foundedYear: 2018,
    employeeCount: "201-500",
    location: "New York, NY",
    fundingTotal: "$237M",
    lastFundingDate: "2024-06-17",
    tags: ["AI/ML", "Video", "Creative", "Generative AI"],
    signals: [
      { id: "s33", type: "funding", title: "Raised $141M Series D", description: "Valuation reached $4B. Led by General Atlantic.", date: "2024-06-17", source: "Bloomberg" },
      { id: "s34", type: "product", title: "Gen-3 Alpha model launch", description: "Next-generation video generation model with improved fidelity.", date: "2024-06-17" },
      { id: "s35", type: "partnership", title: "Entertainment studio partnerships", description: "Deals with major Hollywood studios for AI-assisted VFX.", date: "2024-04-10" },
    ],
  },
  {
    id: "12",
    name: "Resend",
    domain: "resend.com",
    description: "Developer-first email API built for modern applications with beautiful templates, reliable delivery, and a delightful developer experience.",
    industry: "Developer Tools",
    stage: "Series A",
    foundedYear: 2022,
    employeeCount: "11-50",
    location: "San Francisco, CA",
    fundingTotal: "$6.5M",
    lastFundingDate: "2023-09-06",
    tags: ["DevTools", "Email", "API", "SaaS"],
    signals: [
      { id: "s36", type: "product", title: "React Email 2.0 released", description: "Major update to open-source email component library.", date: "2024-05-01" },
      { id: "s37", type: "growth", title: "30K+ developers onboarded", description: "Rapid developer adoption with 10x growth in monthly sends.", date: "2024-08-01" },
      { id: "s38", type: "hiring", title: "Growing engineering team", description: "5 new engineering hires for infrastructure and API development.", date: "2024-09-15" },
    ],
  },
];

export const industries = [
  "All Industries",
  "Artificial Intelligence",
  "Creative AI",
  "Cybersecurity",
  "Data & Analytics",
  "Design Tools",
  "Developer Tools",
  "FinTech",
  "Legal Tech",
  "Productivity",
];

export const stages = [
  "All Stages",
  "Seed",
  "Series A",
  "Series B",
  "Series C",
  "Series D",
  "Series I",
  "Late Stage",
];

export const locations = [
  "All Locations",
  "San Francisco, CA",
  "New York, NY",
  "London, UK",
  "Paris, France",
];

export const employeeRanges = [
  "All Sizes",
  "1-10",
  "11-50",
  "51-200",
  "201-500",
  "501-1000",
  "1001-5000",
  "5001-10000",
];
